agentType: prometheus
type: exporter

name: mysql_collector_plugin
version: 1.0.0

category: 数据库
params:
    - mysql_host
    - mysql_port
    - mysql_user
    - mysql_password
    - exporter_host
    - exporter_port
    - exporter_uri
